module.exports = {
  root: true,
  parser: 'vue-eslint-parser',
  extends: [
    'plugin:vue/recommended',
    'airbnb-base',
    'plugin:flowtype/recommended',
    'prettier',
    'prettier/flowtype',
  ],
  plugins: ['vue', 'import', 'node', 'prettier', 'flowtype'],
  env: {
    node: true,
    es6: true,
    browser: true,
  },
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 2018,
  },
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.vue'],
      },
    },
  },
  rules: {
    'import/no-cycle': 0,
    'import/no-unresolved': 0,
    'import/prefer-default-export': 0,
    'import/extensions': 0,
    'import/order': 0,
    'no-param-reassign': 0,
    'no-use-before-define': 0,
    'no-unused-vars': 0,
    radix: 0,
    'prefer-promise-reject-errors': 0,
    'no-plusplus': 0,
    'no-shadow': 0,
    'consistent-return': 0,
    'vue/no-unused-vars': 0,
    'prefer-destructuring': 0,
    'vue/require-v-for-key': 0,
    'no-continue': 0,
    camelcase: 0,
    'no-underscore-dangle': 0,
    'vue/no-use-v-if-with-v-for': 0,
    'no-multi-assign': 0,
    eqeqeq: 0,
  },
};
